version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - ./scripts/sonar.sh
      - npm build
#      - tar -cvf bundle.tar ./dist/*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
#    - bundle.tar
    - '**/*'
